title:        Sławek Rudawski
tagline:      'Sławek Rudawski'
description:  'Blog programistyczny'
url:          http://slawciu.github.io
version:      1.1.1
author:
  name:       ''
  email:      ''
markdown:     rdiscount
permalink:    pretty
highlighter:  rouge
paginate:     1
gems: [jekyll-paginate]
