title:        Sławek Rudawski
tagline:      'Sławek Rudawski'
description:  ''
url:          https://slawciu.github.io
version:      1.1.1
author:
  name:       'Sławek Rudawski'
  email:      'slawomir.rudawski@gmail.com'
markdown:     rdiscount
permalink:    pretty
highlighter:  rouge
paginate:     5
gems: [jekyll-paginate]
